import { useCallback, useEffect, useState } from 'react';
import { supabase } from '@/db/supabase';
import { arenaSceneImage } from '@/lib/beatvision/arena';
import { sceneTimeline } from '@/lib/beatvision/timeline';
import type { Project, SceneImage, SceneVisualPrompt, WorldStyleBible, CharacterSheet, EnvironmentSheet } from '@/types/types';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { ImageIcon, Loader2, CheckCircle2, XCircle, Sparkles, Upload } from 'lucide-react';
import { toast } from 'sonner';

interface Props { project:Project; prompts:SceneVisualPrompt[]; initialImages:SceneImage[]; initialStyleBible:WorldStyleBible|null; initialCharacterSheet:CharacterSheet|null; initialEnvironmentSheet:EnvironmentSheet|null; realProvidersEnabled:boolean; providerActive:boolean; providerName:string; providerEndpoint:string|null; onProjectUpdate:(u:Partial<Project>)=>void; onSceneImagesUpdate:(i:SceneImage[])=>void; }

export default function GenerateSceneImagesSection({project,prompts,initialImages,initialStyleBible,initialCharacterSheet,initialEnvironmentSheet,onProjectUpdate,onSceneImagesUpdate}:Props){
 const [images,setImages]=useState<SceneImage[]>(initialImages),[bible,setBible]=useState<WorldStyleBible|null>(initialStyleBible),[character,setCharacter]=useState<CharacterSheet|null>(initialCharacterSheet),[environment,setEnvironment]=useState<EnvironmentSheet|null>(initialEnvironmentSheet),[busy,setBusy]=useState<Set<string>>(new Set()),[loading,setLoading]=useState(false);
 const load=useCallback(async()=>{const {data,error}=await supabase.from('scene_images').select('*').eq('project_id',project.id).order('scene_number');if(error)throw error;const next=(data||[]) as SceneImage[];setImages(next);onSceneImagesUpdate(next);},[project.id,onSceneImagesUpdate]);
 useEffect(()=>{onSceneImagesUpdate(initialImages);},[initialImages,onSceneImagesUpdate]);
 const save=async(prompt:SceneVisualPrompt,url:string,raw:any)=>{const existing=images.find(i=>i.scene_visual_prompt_id===prompt.id);let nextVersion=1;if(existing){const {data,error}=await supabase.from('scene_image_versions').select('version_number').eq('scene_image_id',existing.id).order('version_number',{ascending:false}).limit(1).maybeSingle();if(error)throw error;nextVersion=Number(data?.version_number||0)+1;}const record={project_id:project.id,storyboard_scene_id:prompt.storyboard_scene_id,scene_visual_prompt_id:prompt.id,scene_index:prompt.scene_number,scene_number:prompt.scene_number,scene_title:prompt.scene_title,timestamp_range:prompt.timestamp_range,image_url:url,thumbnail_url:null,prompt_used:prompt.main_image_prompt,prompt_summary:prompt.main_image_prompt?.slice(0,300)||null,mood:prompt.mood,camera_framing:prompt.camera_framing,location:prompt.environment_details,character_presence:prompt.character_placement,lighting_direction:prompt.lighting_direction,style_consistency_summary:prompt.style_consistency_notes,real_generated:true,manual_upload:false,placeholder:false,use_placeholder_as_draft_final:false,provider_name:'beatvision-arena',generation_status:'generated',approved:false,rejected:false,pending:false,failed:false,needs_review:true,updated_after_approval:false,active_version:nextVersion,updated_at:new Date().toISOString(),provider_request:{contract_version:'1.1',operation:'sceneImages'},provider_response:raw};let row:SceneImage|null=null;if(existing){const {data,error}=await supabase.from('scene_images').update(record).eq('id',existing.id).select().maybeSingle();if(error)throw error;row=data as SceneImage|null;}else{const {data,error}=await supabase.from('scene_images').insert(record).select().maybeSingle();if(error)throw error;row=data as SceneImage|null;}if(row){const {error}=await supabase.from('scene_image_versions').insert({scene_image_id:row.id,version_number:nextVersion,image_url:url,prompt_used:prompt.main_image_prompt,notes:'BeatVision Arena Pixazo SDXL generation',approved:false});if(error)throw error;}return row;};
 const generate=async(prompt:SceneVisualPrompt)=>{setBusy(x=>new Set(x).add(prompt.id));try{const timeline=sceneTimeline(prompt,5);const response=await arenaSceneImage({project_id:project.id,song_title:project.title,style:project.selected_style,song_duration_seconds:project.song_duration||null,world:{style_bible:bible,character_sheet:character,environment_sheet:environment},storyboard:{songDuration:project.song_duration||0,scenes:[{scene:prompt.scene_number,scene_title:prompt.scene_title,startTime:timeline.startTime,endTime:timeline.endTime,duration_seconds:timeline.duration,visualEvent:prompt.main_image_prompt,cameraDirection:prompt.camera_framing,mood:prompt.mood,location:prompt.environment_details}]},images:{},references:[],forbidden:[bible?.things_to_avoid||''].filter(Boolean)});const item=response?.result?.images?.[0];const url=item?.image_url||item?.url;if(!url)throw new Error('Arena returned no scene image.');const row=await save(prompt,url,response);if(row){setImages(prev=>{const n=prev.some(x=>x.id===row!.id)?prev.map(x=>x.id===row!.id?row!:x):[...prev,row!];onSceneImagesUpdate(n);return n;});toast.success(`Scene ${prompt.scene_number} generated with Arena.`);} }catch(error){const message=error instanceof Error?error.message:typeof error==='string'?error:JSON.stringify(error);console.error('[BeatVision][Arena][sceneImages] generation failed',error);toast.error(message||'Arena image generation failed.');}finally{setBusy(x=>{const n=new Set(x);n.delete(prompt.id);return n;})}};
 const generateAll=async()=>{const approved=prompts.filter(p=>p.approved);if(!approved.length){toast.error('No approved scene prompts found.');return;}await supabase.from('projects').update({status:'Generating Scene Images'}).eq('id',project.id);onProjectUpdate({status:'Generating Scene Images'});for(const prompt of approved){await generate(prompt);await new Promise(r=>setTimeout(r,300));}await load();await supabase.from('projects').update({status:'Scene Images In Review'}).eq('id',project.id);onProjectUpdate({status:'Scene Images In Review'});};
 const approve=async(id:string)=>{await supabase.from('scene_images').update({approved:true,rejected:false,generation_status:'approved',needs_review:false,updated_at:new Date().toISOString()}).eq('id',id);const n=images.map(x=>x.id===id?{...x,approved:true,rejected:false,generation_status:'approved' as const,needs_review:false}:x);setImages(n);onSceneImagesUpdate(n);const complete=prompts.filter(p=>p.approved).every(p=>n.some(i=>i.scene_visual_prompt_id===p.id&&i.approved));if(complete){await supabase.from('projects').update({status:'Ready for Motion',images_approved:true}).eq('id',project.id);onProjectUpdate({status:'Ready for Motion',images_approved:true});}};
 const reject=async(id:string)=>{await supabase.from('scene_images').update({approved:false,rejected:true,generation_status:'rejected'}).eq('id',id);await load();};
 if(loading)return <div className="py-8 flex gap-2 items-center text-muted-foreground"><Loader2 className="w-4 h-4 animate-spin"/>Loading Arena image pipeline…</div>;
 return <div className="space-y-5"><div className="flex items-center gap-3"><ImageIcon className="w-4 h-4 text-blue-400"/><div><p className="text-xs font-mono uppercase tracking-widest text-muted-foreground/60">Arena Scene Image Pipeline</p><p className="text-xs text-muted-foreground/50">Pixazo SDXL is the primary scene-image provider. Existing provider adapters remain optional.</p></div></div><Card><CardContent className="p-4 flex items-center justify-between"><div><p className="text-sm font-semibold">{prompts.filter(p=>p.approved).length} approved scene prompts</p><p className="text-xs text-muted-foreground">Generate one validated visual event per approved scene.</p></div><Button onClick={generateAll} disabled={busy.size>0}><Sparkles className="w-4 h-4 mr-2"/>Generate All with Arena</Button></CardContent></Card><div className="grid grid-cols-1 md:grid-cols-2 gap-4">{prompts.filter(p=>p.approved).map(p=>{const img=images.find(x=>x.scene_visual_prompt_id===p.id);return <Card key={p.id}><CardContent className="p-4 space-y-3"><div className="aspect-video rounded bg-muted overflow-hidden">{img?.image_url&&<img src={img.image_url} className="w-full h-full object-cover"/>}</div><div className="flex items-center justify-between gap-2"><div><p className="text-sm font-medium">Scene {p.scene_number} · {p.scene_title||'Untitled'}</p><Badge className="mt-1">{img?.approved?'approved':img?.real_generated?'generated':'not generated'}</Badge></div><div className="flex gap-2">{!img?.approved&&<Button size="sm" onClick={()=>img?approve(img.id):generate(p)} disabled={busy.has(p.id)}>{busy.has(p.id)?<Loader2 className="w-3 h-3 animate-spin"/>:img?<><CheckCircle2 className="w-3 h-3 mr-1"/>Approve</>:<><Sparkles className="w-3 h-3 mr-1"/>Generate</>}</Button>}{img&&!img.approved&&<Button size="sm" variant="ghost" onClick={()=>reject(img.id)}><XCircle className="w-3 h-3 mr-1"/>Reject</Button>}</div></div>{img?.image_url&&<p className="text-[11px] text-muted-foreground/50">Provider: BeatVision Arena / Pixazo SDXL</p>}</CardContent></Card>})}</div></div>;
}
