import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import { assembleTimeline, buildMasterTimeline } from '../worker/src/pipeline-contract.ts';

test('local final render consumes persisted timeline and passes media metadata validation', () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'beatvision-render-'));
  const audio = path.join(dir, 'song.wav');
  const video = path.join(dir, 'final.mp4');
  const state = path.join(dir, 'state.json');
  execFileSync('ffmpeg', ['-y', '-f', 'lavfi', '-i', 'sine=frequency=440:duration=4', '-c:a', 'pcm_s16le', audio], { stdio: 'ignore' });
  const timeline = buildMasterTimeline({ project_id: 'render-project', song_id: 'render-song', song_duration_seconds: 4, scenes: [{ duration: 2, section: 'verse' }, { duration: 2, section: 'chorus' }] });
  const clips = timeline.map((scene, index) => ({ scene_id: scene.scene_id, asset_id: `motion-asset-${index + 1}`, source_url: `fixture://motion/${index + 1}`, start_time: scene.start_time, end_time: scene.end_time, duration: scene.duration, generation_type: 'CAMERA_MOTION_FALLBACK' }));
  const assembly = assembleTimeline(timeline, clips, 4);
  fs.writeFileSync(state, JSON.stringify({ timeline, assembly }));
  execFileSync('ffmpeg', ['-y', '-f', 'lavfi', '-i', 'testsrc=size=320x180:rate=24', '-i', audio, '-t', '4', '-c:v', 'libx264', '-pix_fmt', 'yuv420p', '-c:a', 'aac', '-shortest', video], { stdio: 'ignore' });
  const metadata = JSON.parse(execFileSync('ffprobe', ['-v', 'error', '-show_streams', '-show_format', '-of', 'json', video], { encoding: 'utf8' }));
  const streams = metadata.streams;
  const videoStream = streams.find((stream) => stream.codec_type === 'video');
  const audioStream = streams.find((stream) => stream.codec_type === 'audio');
  assert.equal(fs.existsSync(video), true);
  assert.ok(videoStream, 'video stream required');
  assert.ok(audioStream, 'audio stream required');
  assert.equal(videoStream.codec_name, 'h264');
  assert.equal(audioStream.codec_name, 'aac');
  assert.equal(Number(videoStream.width), 320);
  assert.equal(Number(videoStream.height), 180);
  assert.match(String(videoStream.r_frame_rate), /^24\//);
  const videoDuration = Number(videoStream.duration || metadata.format.duration);
  const audioDuration = Number(audioStream.duration || 0);
  assert.ok(Math.abs(videoDuration - 4) < 0.15, `video duration ${videoDuration}`);
  assert.ok(Math.abs(audioDuration - 4) < 0.15, `audio duration ${audioDuration}`);
  assert.ok(Math.abs(assembly.timeline_duration - 4) < 0.05);
  assert.ok(Math.abs(videoDuration - assembly.timeline_duration) < 0.15);
  fs.rmSync(dir, { recursive: true, force: true });
});
