const PIXAZO_BASE='https://gateway.pixazo.ai';
const PIXAZO_STATUS=`${PIXAZO_BASE}/v2/requests/status/`;
const SHOTSTACK_BASE='https://api.shotstack.io';
const POLL_MS=10000,MAX_RETRIES=3,MAX_SCENES=64,SUBMIT_TIMEOUT_MS=60000,STATUS_TIMEOUT_MS=30000,STATUS_RETRY_DELAY_MS=30000,STATUS_RETRY_NOTICE=3,MAX_PROVIDER_WAIT_MS=30*60*1000;
const media=(d:any)=>d?.output?.media_url?.[0]||d?.output?.media_url||d?.output||d?.url||null;
const retryable=(s:string)=>/prompt not found|provider ended this request|job ERROR|502|503|504|temporarily unavailable|rate limit|too many requests|timed out|timeout|request was rejected|aborted/i.test(s);
const sceneNo=(scene:any,index:number)=>Number(scene?.scene||index+1);
const durationFor=(scene:any)=>Math.max(2.5,Math.min(Number(scene?.duration_seconds)||4,5.5));
const sourceFor=(job:any,scene:any)=>{const item=job.images.find((x:any)=>Number(x?.scene)===sceneNo(scene,job.index))||job.images[job.index];return item?.image_url||item?.url||item?.data_url||null};

export class BeatVisionAnimationJob{
  state:DurableObjectState;env:any;
  constructor(state:DurableObjectState,env:any){this.state=state;this.env=env;}
  async load(){return(await this.state.storage.get<any>('job'))||null;}
  async save(job:any){await this.state.storage.put('job',job);}
  async event(job:any,event:string,details:any={}){const entry={at:new Date().toISOString(),event,scene:job.active_scene??(job.index+1),attempt:(job.retries||0)+1,...details};job.events=Array.isArray(job.events)?job.events:[];job.events.push(entry);if(job.events.length>100)job.events=job.events.slice(-100);job.last_event=entry;job.last_event_at=entry.at;await this.save(job);}
  async alarm(){
    try{
      const job=await this.load();
      if(!job||['completed','partial','failed'].includes(job.status))return;
      await this.event(job,'alarm_fired',{status:job.status,active_request_id:job.active_request_id||null});
      await this.tick();
    }catch(error){
      const msg=error instanceof Error?error.message:String(error);
      const job=await this.load();
      if(job){job.last_error=msg;job.last_error_at=new Date().toISOString();job.status='running';await this.save(job);await this.state.storage.setAlarm(Date.now()+5000);}else{await this.state.storage.setAlarm(Date.now()+5000);}
    }
  }
  async fetchWithTimeout(input:RequestInfo|URL,init:RequestInit={},timeoutMs=30000){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeoutMs);try{return await fetch(input,{...init,signal:controller.signal});}catch(error){if(error instanceof Error&&error.name==='AbortError')throw new Error(`Provider request timed out after ${timeoutMs}ms.`);throw error;}finally{clearTimeout(timer);}}
  async pushClipOnce(job:any,clip:any){job.clips=Array.isArray(job.clips)?job.clips:[];const key=String(clip.asset_id||'');if(key&&job.clips.some((x:any)=>String(x.asset_id||'')===key))return false;job.clips.push(clip);return true;}
  async failGeneration(job:any,scene:any,source:string,duration:number,msg:string){await this.event(job,'provider_failure',{provider:'pixazo_ltx',error:msg,retry_count:job.retries||0,active_request_id:job.active_request_id||null});job.failed.push({scene:sceneNo(scene,job.index),status:502,error:msg,request_id:job.active_request_id||null});job.index++;job.active_request_id=null;job.active_scene=null;job.active_duration=null;job.retries=0;job.status='running';await this.save(job);await this.state.storage.setAlarm(Date.now());return true;}
  async tick(){const job=await this.load();if(!job||['completed','partial','failed'].includes(job.status))return;try{const scene=job.scenes[job.index];if(!scene){job.status=job.failed.length?'partial':'completed';job.completed_at=new Date().toISOString();await this.event(job,'job_completed',{completed:job.clips.length,failed:job.failed.length,total:job.scenes.length});await this.save(job);return;}const sn=sceneNo(scene,job.index),source=sourceFor(job,scene),duration=durationFor(scene);if(!source){await this.event(job,'missing_image',{scene:sn});job.failed.push({scene:sn,status:'missing_image',error:'No source image.'});job.index++;job.retries=0;await this.save(job);await this.state.storage.setAlarm(Date.now());return;}
      if(!job.active_request_id){await this.event(job,'pixazo_submit_start',{provider:'pixazo_ltx',endpoint:'/ltx-video/v1/image-to-video',duration_seconds:duration,image_source:source.startsWith('data:')?'data_url':'remote_url',timeout_ms:SUBMIT_TIMEOUT_MS});const response=await this.fetchWithTimeout(`${PIXAZO_BASE}/ltx-video/v1/image-to-video`,{method:'POST',headers:{'Content-Type':'application/json','Cache-Control':'no-cache','Ocp-Apim-Subscription-Key':this.env.PIXAZO_API_KEY},body:JSON.stringify({prompt:this.prompt(scene),image_url:source})},SUBMIT_TIMEOUT_MS);const text=await response.text();let data:any;try{data=JSON.parse(text)}catch{data={raw:text}};if(!response.ok)throw new Error(`Pixazo ltx-video ${response.status}: ${String(data?.message||data?.error||text).slice(0,1600)}`);if(!data?.request_id){const url=media(data);if(!url)throw new Error('Pixazo LTX returned no request_id or video URL.');const assetId=`motion:${job.job_id}:scene:${sn}:pixazo:direct`;await this.pushClipOnce(job,{scene:sn,status:'animated',video_url:url,source:'Pixazo free LTX image-to-video',provider:'pixazo',model:'ltx-video',generation_type:'GENERATIVE_VIDEO',asset_id:assetId,requested_duration_seconds:duration,duration_seconds:duration,pixazo_request_id:null});job.index++;job.retries=0;await this.event(job,'scene_completed',{provider:'pixazo_ltx',generation_type:'GENERATIVE_VIDEO',asset_id:assetId,source:'direct_media_url',duration_seconds:duration});await this.save(job);await this.state.storage.setAlarm(Date.now());return;}job.active_request_id=data.request_id;job.active_scene=sn;job.active_duration=duration;job.active_started_at=Date.now();job.retries=0;job.status_retries=0;job.status='running';await this.event(job,'pixazo_request_accepted',{provider:'pixazo_ltx',request_id:data.request_id,scene:sn,timeout_ms:STATUS_TIMEOUT_MS,poll_interval_ms:POLL_MS});await this.save(job);await this.state.storage.setAlarm(Date.now()+POLL_MS);return;}
      if(job.active_started_at&&Date.now()-job.active_started_at>MAX_PROVIDER_WAIT_MS){await this.failGeneration(job,scene,source,duration,`Pixazo LTX job exceeded the 30 minute provider wait limit. Provider request ${job.active_request_id} remained non-terminal.`);return;}const response=await this.fetchWithTimeout(`${PIXAZO_STATUS}${encodeURIComponent(job.active_request_id)}`,{headers:{'Ocp-Apim-Subscription-Key':this.env.PIXAZO_API_KEY,'Cache-Control':'no-cache'}},STATUS_TIMEOUT_MS);const text=await response.text();let data:any;try{data=JSON.parse(text)}catch{data={}};if(!response.ok)throw new Error(`Pixazo ltx-video status ${response.status}: ${text.slice(0,1200)}`);const status=String(data?.status||'').toUpperCase();if(status==='COMPLETED'||status==='SUCCEEDED'){const url=media(data);if(!url)throw new Error('Pixazo LTX completed without media output.');const assetId=`motion:${job.job_id}:scene:${job.active_scene}:pixazo:${job.active_request_id}`;await this.pushClipOnce(job,{scene:job.active_scene,status:'animated',video_url:url,source:'Pixazo free LTX image-to-video',provider:'pixazo',model:'ltx-video',generation_type:'GENERATIVE_VIDEO',asset_id:assetId,requested_duration_seconds:job.active_duration,duration_seconds:job.active_duration,pixazo_request_id:job.active_request_id});await this.event(job,'scene_completed',{provider:'pixazo_ltx',generation_type:'GENERATIVE_VIDEO',asset_id:assetId,request_id:job.active_request_id,duration_seconds:job.active_duration,elapsed_ms:Date.now()-(job.active_started_at||Date.now())});job.index++;job.active_request_id=null;job.active_scene=null;job.active_duration=null;job.retries=0;job.status_retries=0;job.status='running';await this.save(job);await this.state.storage.setAlarm(Date.now());return;}if(['ERROR','FAILED','CANCELLED'].includes(status)){await this.failGeneration(job,scene,source,duration,`Pixazo ltx-video job ${status}: ${String(data?.error||'provider error').slice(0,1600)}`);return;}await this.save(job);await this.state.storage.setAlarm(Date.now()+POLL_MS);
    }catch(err){const msg=err instanceof Error?err.message:String(err);if(job.active_request_id){job.status_retries=(job.status_retries||0)+1;job.status='waiting_provider_status';await this.event(job,'provider_status_uncertain',{provider:'pixazo_ltx',active_request_id:job.active_request_id,status_retries:job.status_retries,error:msg,recovery:'continue_polling_same_provider_request'});await this.save(job);await this.state.storage.setAlarm(Date.now()+(job.status_retries>=STATUS_RETRY_NOTICE?STATUS_RETRY_DELAY_MS:POLL_MS));return;}job.retries=(job.retries||0)+1;await this.event(job,'tick_error',{error:msg,retry_count:job.retries,active_request_id:null});const scene=job.scenes[job.index],source=sourceFor(job,scene),duration=durationFor(scene);if(job.retries<MAX_RETRIES&&retryable(msg)){await this.save(job);await this.state.storage.setAlarm(Date.now()+1500*job.retries);return;}if(source){await this.failGeneration(job,scene,source,duration,msg);return;}job.failed.push({scene:sceneNo(scene,job.index),status:502,error:msg,request_id:null});job.index++;job.retries=0;await this.save(job);await this.state.storage.setAlarm(Date.now());}}
  prompt(scene:any){return ['BeatVision cinematic music-video motion shot.','Preserve the approved character, environment, composition and visual identity.','Natural subtle cinematic camera movement, realistic motion, coherent anatomy, no text, logos, watermarks or captions.',`Storyboard: ${JSON.stringify(scene).slice(0,3500)}`].join('\n');}
  async fetch(req:Request){if(req.method==='GET'){const job=await this.load();if(job&&job.status==='queued'){const alarm=await this.state.storage.getAlarm();if(alarm==null)await this.state.storage.setAlarm(Date.now()+1000);}return job||{status:'not_found'};}if(req.method!=='POST')return new Response('Method Not Allowed',{status:405});const body:any=await req.json(),existing=await this.load();if(existing)return Response.json(existing);const scenes=Array.isArray(body?.storyboard?.scenes)?body.storyboard.scenes.slice(0,MAX_SCENES):[],images=Array.isArray(body?.images?.images)?body.images.images:[];if(!scenes.length||!images.length)return Response.json({ok:false,error:'Animation job requires storyboard scenes and generated images.'},{status:400});const imageScenes=new Set(images.map((image:any,index:number)=>sceneNo(image,index)));const missingScenes=scenes.map((scene:any,index:number)=>sceneNo(scene,index)).filter((scene:number)=>!imageScenes.has(scene));if(missingScenes.length)return Response.json({ok:false,status:'invalid_input',error:'Animation job requires a generated image for every storyboard scene.',missing_scenes:missingScenes,required_scene_count:scenes.length,provided_image_count:images.length},{status:422});const job={job_id:body.job_id,status:'queued',created_at:new Date().toISOString(),index:0,scenes,images,clips:[],failed:[],retries:0,status_retries:0,active_request_id:null,active_scene:null,active_duration:null,active_started_at:null,events:[],last_event:null,last_event_at:null};await this.event(job,'job_created',{total_scenes:scenes.length,total_images:images.length,max_scenes:MAX_SCENES,max_retries:MAX_RETRIES,submit_timeout_ms:SUBMIT_TIMEOUT_MS,status_timeout_ms:STATUS_TIMEOUT_MS,poll_interval_ms:POLL_MS,status_retry_delay_ms:STATUS_RETRY_DELAY_MS});await this.save(job);await this.state.storage.setAlarm(Date.now()+1000);return Response.json(job,{status:202});}
}
