import { assertSufficientCoverage, buildCoverageManifest, targetDurationFromPayload, COVERAGE_EPSILON_SECONDS, type ValidatedMotionClip } from './render-integrity';

const BASE='https://api.shotstack.io';
const STAGE=`${BASE}/edit/stage`;
const INGEST_STAGE=`${BASE}/ingest/stage`;
const PROBE=`${BASE}/v1/probe`;

function cors(r:Request,e:any){const o=r.headers.get('Origin')||'';const allowed=String(e.ALLOWED_ORIGIN||'').split(',').map((x:string)=>x.trim()).filter(Boolean);return{'Access-Control-Allow-Origin':o&&(!allowed.length||allowed.includes(o))?o:(allowed[0]||'*'),'Vary':'Origin','Access-Control-Allow-Methods':'GET,POST,OPTIONS','Access-Control-Allow-Headers':'Content-Type,X-BeatVision-Contract,Authorization,X-BeatVision-Request','Access-Control-Max-Age':'86400'};}
function json(r:Request,e:any,d:unknown,status=200){return new Response(JSON.stringify(d,null,2),{status,headers:{'Content-Type':'application/json',...cors(r,e)}});}
function auth(r:Request,e:any){return !e.GATEWAY_TOKEN||r.headers.get('Authorization')===`Bearer ${e.GATEWAY_TOKEN}`;}
function dataUrlToBlob(value:string){const comma=value.indexOf(',');if(comma<0||!value.startsWith('data:'))throw new Error('Invalid data URL');const header=value.slice(5,comma),mime=header.split(';')[0]||'application/octet-stream',base64=value.slice(comma+1).replace(/\s/g,''),binary=atob(base64),bytes=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)bytes[i]=binary.charCodeAt(i);return new Blob([bytes],{type:mime});}
async function shotstackFetch(path:string,key:string,init:RequestInit={}){const headers=new Headers(init.headers||{});headers.set('x-api-key',key);headers.set('Accept','application/json');const response=await fetch(`${BASE}${path}`,{...init,headers});const text=await response.text();let data:any;try{data=JSON.parse(text)}catch{data={raw:text}}if(!response.ok)throw Object.assign(new Error(`Shotstack ${response.status}: ${String(data?.response?.error||data?.message||data?.error||text).slice(0,1800)}`),{status:response.status,provider_response:data});return data;}
async function uploadDataUrl(value:string,key:string,filename:string){const blob=dataUrlToBlob(value),ticket=await shotstackFetch('/ingest/stage/upload',key,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({filename})}),id=ticket?.data?.id||ticket?.data?.attributes?.id,signed=ticket?.data?.attributes?.url;if(!id||!signed)throw new Error('Shotstack ingest did not return a signed upload URL.');const put=await fetch(signed,{method:'PUT',headers:{'Content-Type':blob.type||'application/octet-stream'},body:blob});if(!put.ok)throw new Error(`Shotstack source upload returned ${put.status}.`);const deadline=Date.now()+90000;while(Date.now()<deadline){const status=await shotstackFetch(`/ingest/stage/sources/${encodeURIComponent(id)}`,key),attrs=status?.data?.attributes||{};if(attrs.status==='ready'&&attrs.source)return attrs.source as string;if(['failed','error'].includes(String(attrs.status||'').toLowerCase()))throw new Error(`Shotstack source ingest failed: ${String(attrs.error||attrs.status)}`);await new Promise(resolve=>setTimeout(resolve,2000));}throw new Error('Shotstack source ingest timed out after 90 seconds.');}
export async function resolveShotstackSource(value:unknown,key:string,filename:string){if(typeof value!=='string'||!value)throw new Error(`Missing ${filename} source.`);if(value.startsWith('data:'))return uploadDataUrl(value,key,filename);if(/^https?:\/\//i.test(value))return value;throw new Error(`Unsupported ${filename} source. Expected an https URL or data URL.`);}
function probeDuration(data:any){const metadata=data?.response?.metadata||data?.metadata||{};const streams=Array.isArray(metadata.streams)?metadata.streams:[];const durations=streams.map((s:any)=>Number(s?.duration)).filter((n:number)=>Number.isFinite(n)&&n>0);const formatDuration=Number(metadata?.format?.duration);if(Number.isFinite(formatDuration)&&formatDuration>0)durations.push(formatDuration);return durations.length?Math.max(...durations):0;}
async function probeVideo(url:string,key:string){const data=await shotstackFetch(`/v1/probe/${encodeURIComponent(url)}`,key);const duration=probeDuration(data);if(!(duration>0))throw new Error('MEDIA_INTEGRITY_PROBE_NO_DURATION');return{duration_seconds:duration,metadata:data?.response?.metadata||data?.metadata||null};}
function extractMotionClips(payload:any){const candidates=payload?.motion?.clips||payload?.motion?.result?.clips;if(Array.isArray(candidates))return candidates.filter((x:any)=>x?.video_url||x?.url);const single=payload?.motion?.video_url||payload?.motion?.result?.video_url||payload?.motion?.url||payload?.motion?.result?.url;return typeof single==='string'&&single?[{scene:1,status:'animated',video_url:single,provider:payload?.motion?.provider,model:payload?.motion?.model,source:payload?.motion?.source,generation_type:payload?.motion?.generation_type}]:[];}
export async function getShotstackRenderStatus(r:Request,e:any,renderId:string,targetDuration:number){
 const id=r.headers.get('X-BeatVision-Request')||crypto.randomUUID();
 if(!auth(r,e))return json(r,e,{ok:false,error:'Unauthorized',request_id:id},401);
 const key=e.SHOTSTACK_API_KEY;
 if(!key)return json(r,e,{ok:false,contract_version:'1.1',capability:'video',status:'provider_unavailable',request_id:id,error:'Shotstack Sandbox is not configured. Configure SHOTSTACK_API_KEY as a Worker secret.'},503);
 if(!/^[A-Za-z0-9-]+$/.test(renderId))return json(r,e,{ok:false,error:'Invalid render ID.',request_id:id},400);
 try{
  const data=await shotstackFetch(`/edit/stage/render/${encodeURIComponent(renderId)}`,key);
  const response=data?.response||data?.data||{};
  const status=String(response.status||'').toLowerCase();
  if(status==='done'){
   const duration=Number(response.duration);
   if(!(duration>0)||!(targetDuration>0)||Math.abs(duration-targetDuration)>0.35)return json(r,e,{ok:true,contract_version:'1.1',capability:'video',provider:'shotstack',status:'failed',request_id:id,result:{status:'failed',render_id:renderId,error:`FINAL_MEDIA_DURATION_MISMATCH: expected=${targetDuration.toFixed(3)}s actual=${Number.isFinite(duration)?duration.toFixed(3):'unknown'}s`}});
  }
  if(['failed','error'].includes(status))return json(r,e,{ok:true,contract_version:'1.1',capability:'video',provider:'shotstack',status:'failed',request_id:id,result:{status:'failed',render_id:renderId,error:String(response.error||status).slice(0,1800)}});
  return json(r,e,{ok:true,contract_version:'1.1',capability:'video',provider:'shotstack',environment:'sandbox',delivery:status==='done'?'temporary_url':'render_id',watermark:true,request_id:id,result:{status:status||'unknown',render_id:renderId,video_url:status==='done'?response.url:null,preview_url:status==='done'?response.url:null,duration_seconds:Number(response.duration)||null,target_duration_seconds:targetDuration,render_integrity:status==='done'?'PASS':'PENDING'}});
 }catch(error){return json(r,e,{ok:false,contract_version:'1.1',capability:'video',provider:'shotstack',status:'provider_error',request_id:id,render_id:renderId,error:String(error instanceof Error?error.message:error).slice(0,2000)},502);}
}

export default {async fetch(r:Request,e:any){if(r.method==='OPTIONS')return new Response(null,{status:204,headers:cors(r,e)});const url=new URL(r.url);if(url.pathname!=='/v1/video/assemble')return json(r,e,{ok:false,error:'Not found'},404);const id=r.headers.get('X-BeatVision-Request')||crypto.randomUUID();if(!auth(r,e))return json(r,e,{ok:false,error:'Unauthorized',request_id:id},401);if(r.method!=='POST')return json(r,e,{ok:false,error:'POST required',request_id:id},405);const key=e.SHOTSTACK_API_KEY;if(!key)return json(r,e,{ok:false,contract_version:'1.1',capability:'video',provider:'shotstack',status:'provider_unavailable',request_id:id,error:'Shotstack Sandbox is not configured. Configure SHOTSTACK_API_KEY as a Worker secret.'},503);let body:any;try{body=await r.json()}catch{return json(r,e,{ok:false,error:'Invalid JSON body',request_id:id},400);}if(body?.contract_version!=='1.1'||body?.operation!=='assemble')return json(r,e,{ok:false,error:'Expected BeatVision contract 1.1 assemble operation.',request_id:id},400);const payload=body.payload||{},motionClips=extractMotionClips(payload),storyboardScenes=Array.isArray(payload.storyboard?.scenes)?payload.storyboard.scenes:Array.isArray(payload.storyboard?.visual_beats)?payload.storyboard.visual_beats:[];if(!storyboardScenes.length)return json(r,e,{ok:false,contract_version:'1.1',capability:'video',status:'invalid_input',request_id:id,error:'Assembly requires the approved storyboard master timeline.'},400);if(!motionClips.length)return json(r,e,{ok:false,contract_version:'1.1',capability:'video',status:'invalid_input',request_id:id,error:'Assembly requires generated motion clips.'},400);const started=Date.now();try{
 const targetDuration=targetDurationFromPayload(payload,Number(payload.storyboard?.songDuration||payload.storyboard?.song_duration||0));if(!(targetDuration>0))throw new Error('MEDIA_INTEGRITY_MISSING_TARGET_DURATION');
 
 const scenePlan=new Map<number,{start:number,end:number}>();for(const scene of storyboardScenes){const n=Number(scene?.scene);const start=Number(scene?.startTime??scene?.start_time??0);const end=Number(scene?.endTime??scene?.end_time??0);if(!Number.isInteger(n)||n<1||!Number.isFinite(start)||!Number.isFinite(end)||end<=start)throw new Error(`MEDIA_INTEGRITY_INVALID_STORYBOARD_TIMING:${n||'unknown'}`);scenePlan.set(n,{start,end});}
 const resolved:ValidatedMotionClip[]=[];const seenSources=new Set<string>(),seenAssets=new Set<string>(),seenScenes=new Set<number>();
 for(let i=0;i<motionClips.length;i++){const clip=motionClips[i],scene=Number(clip?.scene||i+1),assetId=String(clip?.asset_id||'').trim(),sourceValue=clip?.video_url||clip?.url,plan=scenePlan.get(scene);if(!Number.isInteger(scene)||scene<1)throw new Error(`MEDIA_INTEGRITY_INVALID_SCENE_ID:${i+1}`);if(!plan)throw new Error(`MEDIA_INTEGRITY_MOTION_SCENE_NOT_IN_STORYBOARD:${scene}`);if(!assetId)throw new Error(`MEDIA_INTEGRITY_MISSING_ASSET_ID:${scene}`);if(seenScenes.has(scene))throw new Error(`MEDIA_INTEGRITY_DUPLICATE_SCENE:${scene}`);if(seenAssets.has(assetId))throw new Error(`MEDIA_INTEGRITY_DUPLICATE_ASSET:${assetId}`);const source=await resolveShotstackSource(sourceValue,key,`beatvision-motion-${i+1}.mp4`);if(seenSources.has(source))throw new Error(`MEDIA_INTEGRITY_DUPLICATE_SOURCE:${scene}`);const probed=await probeVideo(source,key),allocated=plan.end-plan.start;if(probed.duration_seconds+COVERAGE_EPSILON_SECONDS<allocated)throw new Error(`MEDIA_INTEGRITY_CLIP_TOO_SHORT_FOR_TIMELINE:${scene}:actual=${probed.duration_seconds.toFixed(3)}:required=${allocated.toFixed(3)}`);const generationType=clip?.generation_type==='GENERATIVE_VIDEO'||String(clip?.provider||'').toLowerCase().includes('pixazo')?'GENERATIVE_VIDEO':null;if(!generationType)throw new Error(`MEDIA_INTEGRITY_UNKNOWN_GENERATION_TYPE:${scene}`);seenSources.add(source);seenAssets.add(assetId);seenScenes.add(scene);resolved.push({scene,asset_id:assetId,source_url:source,generation_type:generationType,actual_duration_seconds:probed.duration_seconds,requested_duration_seconds:Number(clip?.requested_duration_seconds||clip?.duration_seconds)||undefined,timeline_start_seconds:plan.start,timeline_end_seconds:plan.end,provider:clip?.provider,model:clip?.model});}
 if(seenScenes.size!==scenePlan.size)throw new Error(`MEDIA_INTEGRITY_MISSING_MOTION_FOR_STORYBOARD_SCENE:expected=${scenePlan.size}:actual=${seenScenes.size}`);
 const manifest=buildCoverageManifest(resolved,targetDuration);assertSufficientCoverage(manifest);
 const videoClips:any[]=manifest.clips.sort((a,b)=>(a.timeline_start_seconds||0)-(b.timeline_start_seconds||0)).map((item)=>{const start=Number(item.timeline_start_seconds),end=Number(item.timeline_end_seconds),length=end-start;return{asset:{type:'video',src:item.source_url,transcode:true},start,length,fit:'crop'};});
 const audioInput=payload.audio_base64||payload.audio_data||null,audioSrc=audioInput?await resolveShotstackSource(audioInput,key,'beatvision-song.mp3'):null;const tracks:any[]=[{clips:videoClips}],timeline:any={background:'#000000',tracks};if(audioSrc)timeline.soundtrack={src:audioSrc,volume:1};const edit={timeline,output:{format:'mp4',resolution:'hd',aspectRatio:'16:9',fps:25}};const queued=await shotstackFetch('/edit/stage/render',key,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(edit)}),renderId=queued?.response?.id;if(!renderId)throw new Error('Shotstack did not return a render ID.');
 // Shotstack rendering is asynchronous. Return immediately with the durable render ID.
 // The caller polls getShotstackRenderStatus instead of holding this Worker open.
 return json(r,e,{ok:true,contract_version:'1.1',capability:'video',provider:'shotstack',environment:'sandbox',delivery:'render_id',watermark:true,status:'queued',latency_ms:Date.now()-started,request_id:id,result:{status:'queued',render_id:renderId,target_duration_seconds:targetDuration,timeline_clips:videoClips.length,source_clips:manifest.unique_asset_count,source_audio:!!audioSrc,coverage_manifest:manifest,timeline_mode:'STORYBOARD_MASTER_TIMELINE'}});
 } catch(err){const msg=err instanceof Error?err.message:String(err),providerResponse=err&&typeof err==='object'?(err as any).provider_response:null;const status=/MEDIA_INTEGRITY|INSUFFICIENT_UNIQUE_VISUAL_COVERAGE|FINAL_MEDIA_DURATION_MISMATCH/.test(msg)?422:502;return json(r,e,{ok:false,contract_version:'1.1',capability:'video',provider:'shotstack',environment:'sandbox',status:status===422?'media_integrity_rejected':'provider_error',request_id:id,latency_ms:Date.now()-started,error:msg.slice(0,2000),provider_response:providerResponse},status);}}
};
