interface Env{DB:D1Database;AI:Ai;ASSETS:Fetcher;PIXAZO_API_KEY:string;SHOTSTACK_API_KEY:string;AUTH_RL:RateLimit;WORLD_RL:RateLimit;IMAGE_RL:RateLimit;RENDER_RL:RateLimit}
const AI_MODEL="@cf/meta/llama-3.1-8b-instruct-fp8";
const PIXAZO="https://gateway.pixazo.ai/flux-1-schnell/v1/getData";
const INGEST="https://api.shotstack.io/ingest/v1";
const EDIT="https://api.shotstack.io/edit/v1";
const SESSION_MS=30*86400000;
const j=(x:unknown,s=200,h:HeadersInit={})=>new Response(JSON.stringify(x),{status:s,headers:{"content-type":"application/json","cache-control":"no-store",...h}});
class AppError extends Error{constructor(public message:string,public status=500,public stage="request"){super(message)}}
const providerError=(message:string,stage:string)=>new AppError(message,502,stage);
const n=()=>Date.now();
const limit=async(e:Env,k:keyof Pick<Env,"AUTH_RL"|"WORLD_RL"|"IMAGE_RL"|"RENDER_RL">,key:string)=>{const r=await e[k].limit({key});if(!r.success)throw j({success:false,error:"Rate limit exceeded"},429,{"retry-after":"60"})};
let schemaReady:Promise<void>|null=null;
const ensureSchema=(e:Env)=>schemaReady??=(schema(e).catch(err=>{schemaReady=null;throw err}));
const cookie=(r:Request,name:string)=>{const p=name+"=";const x=(r.headers.get("cookie")||"").split(";").map(x=>x.trim()).find(x=>x.startsWith(p));return x?decodeURIComponent(x.slice(p.length)):null};
const b64=(x:Uint8Array)=>btoa(String.fromCharCode(...x));
const unb64=(x:string)=>Uint8Array.from(atob(x),c=>c.charCodeAt(0));
async function sha(x:string){return b64(new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(x))))}
async function pwd(x:string,s:Uint8Array){const k=await crypto.subtle.importKey("raw",new TextEncoder().encode(x),"PBKDF2",false,["deriveBits"]);return b64(new Uint8Array(await crypto.subtle.deriveBits({name:"PBKDF2",salt:s.buffer as ArrayBuffer,iterations:100000,hash:"SHA-256"},k,256)))}
async function schema(e:Env){await e.DB.batch([
e.DB.prepare("CREATE TABLE IF NOT EXISTS bv_users(id TEXT PRIMARY KEY,username TEXT NOT NULL UNIQUE,password_hash TEXT NOT NULL,password_salt TEXT NOT NULL,created_at INTEGER NOT NULL)"),
e.DB.prepare("CREATE TABLE IF NOT EXISTS bv_sessions(id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES bv_users(id) ON DELETE CASCADE,token_hash TEXT NOT NULL UNIQUE,expires_at INTEGER NOT NULL,created_at INTEGER NOT NULL)"),
e.DB.prepare("CREATE TABLE IF NOT EXISTS bv_projects(id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES bv_users(id) ON DELETE CASCADE,title TEXT NOT NULL,artist TEXT NOT NULL DEFAULT '',lyrics TEXT NOT NULL DEFAULT '',creative_direction TEXT NOT NULL DEFAULT '',notes TEXT NOT NULL DEFAULT '',audio_source_id TEXT,audio_source_url TEXT,audio_name TEXT,audio_type TEXT,audio_size INTEGER,audio_duration REAL,hero_image_url TEXT,status TEXT NOT NULL DEFAULT 'draft',created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL)"),
e.DB.prepare("CREATE TABLE IF NOT EXISTS bv_world_reports(id TEXT PRIMARY KEY,project_id TEXT NOT NULL UNIQUE REFERENCES bv_projects(id) ON DELETE CASCADE,payload_json TEXT NOT NULL,created_at INTEGER NOT NULL)"),
e.DB.prepare("CREATE TABLE IF NOT EXISTS bv_renders(id TEXT PRIMARY KEY,project_id TEXT NOT NULL REFERENCES bv_projects(id) ON DELETE CASCADE,provider_render_id TEXT NOT NULL UNIQUE,status TEXT NOT NULL,output_url TEXT,poster_url TEXT,error_message TEXT,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL)"),
e.DB.prepare("CREATE INDEX IF NOT EXISTS bv_sessions_token_idx ON bv_sessions(token_hash)"),e.DB.prepare("CREATE INDEX IF NOT EXISTS bv_projects_user_idx ON bv_projects(user_id,updated_at DESC)"),e.DB.prepare("CREATE INDEX IF NOT EXISTS bv_renders_project_idx ON bv_renders(project_id,created_at DESC)")])}
async function body(r:Request){const raw=await r.text();if(new TextEncoder().encode(raw).byteLength>262144)throw Error("Request body too large");try{const v=JSON.parse(raw);if(!v||typeof v!=="object"||Array.isArray(v))throw Error("Invalid JSON body");return v as Record<string,unknown>}catch{throw Error("Invalid JSON body")}}
async function user(r:Request,e:Env){const t=cookie(r,"bv_session");if(!t)return null;return await e.DB.prepare("SELECT u.id,u.username FROM bv_sessions s JOIN bv_users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>? LIMIT 1").bind(await sha(t),n()).first<{id:string;username:string}>()}
async function auth(r:Request,e:Env){const u=await user(r,e);if(!u)throw j({success:false,error:"Authentication required"},401);return u}
function reqs(x:unknown,name:string,min:number,max:number){if(typeof x!=="string"||x.trim().length<min||x.length>max)throw Error(name+" is invalid");return x.trim()}
async function session(e:Env,id:string,secure:boolean){const now=n(),t=crypto.randomUUID()+crypto.randomUUID();await e.DB.batch([e.DB.prepare("DELETE FROM bv_sessions WHERE user_id=? AND expires_at<=?").bind(id,now),e.DB.prepare("INSERT INTO bv_sessions(id,user_id,token_hash,expires_at,created_at) VALUES(?,?,?,?,?)").bind(crypto.randomUUID(),id,await sha(t),now+SESSION_MS,now)]);return "bv_session="+encodeURIComponent(t)+"; Path=/; HttpOnly; SameSite=Lax; Max-Age="+(SESSION_MS/1000)+(secure?"; Secure":"")}
async function project(e:Env,u:{id:string},id:string){return await e.DB.prepare("SELECT * FROM bv_projects WHERE id=? AND user_id=?").bind(id,u.id).first<any>()}
function parseWorld(x:unknown){
const s=typeof x==="string"?x:JSON.stringify(x);
const a=s.indexOf("{"),z=s.lastIndexOf("}");
if(a<0||z<=a)throw providerError("Workers AI returned non-JSON world data","world.parse");
let v:unknown;
try{v=JSON.parse(s.slice(a,z+1))}catch{throw providerError("Workers AI returned invalid JSON for the world report","world.parse")}
if(!v||typeof v!=="object"||Array.isArray(v))throw providerError("Workers AI returned a non-object world report","world.parse");
const o=v as Record<string,unknown>;
for(const k of ["song_summary","emotional_arc","visual_language","environments","characters","style_bible","first_scene_prompt"])
if(typeof o[k]!=="string"&&k!=="environments"&&k!=="visual_language"&&k!=="characters"&&k!=="style_bible")
throw providerError("Workers AI returned an incomplete world report","world.validate");
if(!Array.isArray(o.environments)||o.environments.length<3)throw providerError("Workers AI returned too few environments","world.validate");
if(typeof o.first_scene_prompt!=="string"||!o.first_scene_prompt.trim()||o.first_scene_prompt.length>1800)
throw providerError("Workers AI returned an invalid first scene prompt","world.validate");
return o
}
async function world(e:Env,p:any){const prompt=[
"You are BeatVision, a visual-world intelligence engine for music videos. Return ONLY JSON.",
"Required keys: song_summary, emotional_arc, visual_language, environments, characters, style_bible, first_scene_prompt.",
"visual_language keys: palette, lighting, cinematography, texture.",
"style_bible keys: visual_rules, continuity_rules, camera_rules, negative_rules.",
"environments: at least 3 cinematic environments. characters: concrete appearance and wardrobe.",
"first_scene_prompt: production-ready image prompt under 1800 characters.",
"Title: "+p.title,"Artist: "+p.artist,"Lyrics: "+p.lyrics.slice(0,12000),
"Creative direction: "+p.creative_direction.slice(0,4000),"Notes: "+p.notes.slice(0,4000)].join("\n");
let ai:any;
try{
ai=await e.AI.run(AI_MODEL,{prompt,max_tokens:2048,temperature:0.2,response_format:{type:"json_object"}});
}catch{throw providerError("Workers AI world generation failed","world.ai")}
const output=typeof ai==="string"?ai:typeof ai?.response==="string"?ai.response:"";
if(!output.trim())throw providerError("Workers AI returned no world report","world.ai");
return parseWorld(output)}
async function pixazo(e:Env,prompt:string){const r=await fetch(PIXAZO,{method:"POST",signal:AbortSignal.timeout(30000),headers:{"Content-Type":"application/json","Cache-Control":"no-cache","Ocp-Apim-Subscription-Key":e.PIXAZO_API_KEY},body:JSON.stringify({prompt:prompt.slice(0,2048),num_steps:4,width:1024,height:576})});const d=await r.json().catch(()=>null) as any;if(!r.ok||typeof d?.output!=="string")throw providerError("Pixazo image generation failed","image.pixazo");return d.output}
async function upload(e:Env,name:string){const r=await fetch(INGEST+"/upload",{method:"POST",signal:AbortSignal.timeout(30000),headers:{"Accept":"application/json","Content-Type":"application/json","x-api-key":e.SHOTSTACK_API_KEY},body:JSON.stringify({filename:name.slice(0,160)})});const d=await r.json().catch(()=>null) as any;if(!r.ok||!d?.data?.id||!d?.data?.attributes?.url)throw providerError("Shotstack upload setup failed","audio.upload");return{source_id:d.data.id,upload_url:d.data.attributes.url}}
async function source(e:Env,id:string){const r=await fetch(INGEST+"/sources/"+encodeURIComponent(id),{signal:AbortSignal.timeout(15000),headers:{"Accept":"application/json","x-api-key":e.SHOTSTACK_API_KEY}});const d=await r.json().catch(()=>null) as any;if(!r.ok||!d?.data?.attributes)throw providerError("Shotstack source lookup failed","audio.source");return d.data.attributes}
async function render(e:Env,p:any){const edit={timeline:{soundtrack:{src:p.audio_source_url,volume:1},background:"#000",tracks:[{clips:[{asset:{type:"image",src:p.hero_image_url},start:0,length:Math.max(1,Math.min(Number(p.audio_duration)||1,3600)),fit:"cover",effect:"zoomIn"}]}]},output:{format:"mp4",resolution:"hd",aspectRatio:"16:9",fps:25,quality:"medium",repeat:false,mute:false,poster:{capture:1}}};const r=await fetch(EDIT+"/render",{method:"POST",signal:AbortSignal.timeout(30000),headers:{"Content-Type":"application/json","Accept":"application/json","x-api-key":e.SHOTSTACK_API_KEY},body:JSON.stringify(edit)});const d=await r.json().catch(()=>null) as any;if(!r.ok||!d?.response?.id)throw providerError("Shotstack render submission failed","render.submit");return d.response.id}
async function renderStatus(e:Env,id:string){const r=await fetch(EDIT+"/render/"+encodeURIComponent(id),{signal:AbortSignal.timeout(15000),headers:{"Accept":"application/json","x-api-key":e.SHOTSTACK_API_KEY}});const d=await r.json().catch(()=>null) as any;if(!r.ok||!d?.response)throw providerError("Shotstack render status failed","render.status");return d.response}
export default{async fetch(r:Request,e:Env){const requestId=crypto.randomUUID();let stage="request";try{await ensureSchema(e);const u=new URL(r.url),p=u.pathname,m=r.method,secure=u.protocol==="https:";
if(p==="/api/health")return j({success:true,build:"ground-zero-0.1.0",intelligence:AI_MODEL,image:"pixazo-flux-1-schnell",video:"shotstack-v1",request_id:requestId});
if(p==="/api/auth/register"&&m==="POST"){const b=await body(r),un=reqs(b.username,"username",3,32),pw=reqs(b.password,"password",10,128);await limit(e,"AUTH_RL","register:"+un.toLowerCase());if(!/^[A-Za-z0-9_]{3,32}$/.test(un))return j({success:false,error:"Invalid username"},400);if(await e.DB.prepare("SELECT id FROM bv_users WHERE username=?").bind(un).first())return j({success:false,error:"Username unavailable"},409);const s=crypto.getRandomValues(new Uint8Array(16)),id=crypto.randomUUID();await e.DB.prepare("INSERT INTO bv_users VALUES(?,?,?,?,?)").bind(id,un,await pwd(pw,s),b64(s),n()).run();return j({success:true,user:{id,username:un}},201,{"set-cookie":await session(e,id,secure)})}
if(p==="/api/auth/login"&&m==="POST"){const b=await body(r),un=reqs(b.username,"username",3,32),pw=reqs(b.password,"password",10,128);await limit(e,"AUTH_RL","login:"+un.toLowerCase());const x=await e.DB.prepare("SELECT * FROM bv_users WHERE username=?").bind(un).first<any>();if(!x||await pwd(pw,unb64(x.password_salt))!==x.password_hash)return j({success:false,error:"Invalid credentials"},401);return j({success:true,user:{id:x.id,username:x.username}},200,{"set-cookie":await session(e,x.id,secure)})}
if(p==="/api/auth/logout"&&m==="POST"){const t=cookie(r,"bv_session");if(t)await e.DB.prepare("DELETE FROM bv_sessions WHERE token_hash=?").bind(await sha(t)).run();return j({success:true},200,{"set-cookie":"bv_session=; Path=/; HttpOnly; SameSite=Lax; Max-Age=0"})}
if(p==="/api/auth/me")return j({success:true,user:await user(r,e)});
if(p==="/api/projects"&&m==="POST"){const u=await auth(r,e),b=await body(r),title=reqs(b.title,"title",1,200),id=crypto.randomUUID();await e.DB.prepare("INSERT INTO bv_projects(id,user_id,title,artist,lyrics,creative_direction,notes,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)").bind(id,u.id,title,String(b.artist||"").slice(0,200),String(b.lyrics||"").slice(0,20000),String(b.creative_direction||"").slice(0,6000),String(b.notes||"").slice(0,6000),n(),n()).run();return j({success:true,project:{id,title}},201)}
let x=p.match(/^\/api\/projects\/([^/]+)\/(world|image|render)$/);if(x&&m==="POST"){const u=await auth(r,e),q=await project(e,u,x[1]);if(!q)return j({success:false,error:"Project not found"},404);if(x[2]==="world"){stage="world";await limit(e,"WORLD_RL","user:"+u.id+":world");const w=await world(e,q);await e.DB.prepare("INSERT INTO bv_world_reports VALUES(?,?,?,?) ON CONFLICT(project_id) DO UPDATE SET payload_json=excluded.payload_json,created_at=excluded.created_at").bind(crypto.randomUUID(),q.id,JSON.stringify(w),n()).run();return j({success:true,report:w})}if(x[2]==="image"){stage="image";await limit(e,"IMAGE_RL","user:"+u.id+":image");const w=await e.DB.prepare("SELECT payload_json FROM bv_world_reports WHERE project_id=?").bind(q.id).first<any>();if(!w)return j({success:false,error:"Reveal the world first"},409);const v=JSON.parse(w.payload_json),img=await pixazo(e,String(v.first_scene_prompt||v.song_summary||"cinematic music video"));await e.DB.prepare("UPDATE bv_projects SET hero_image_url=?,status='image_ready',updated_at=? WHERE id=?").bind(img,n(),q.id).run();return j({success:true,image_url:img})}stage="render";if(!q.hero_image_url||!q.audio_source_url||!q.audio_duration)return j({success:false,error:"Image and prepared audio are required"},409);await limit(e,"RENDER_RL","user:"+u.id+":render");const now=n();if(q.status==="rendering"){const active=await e.DB.prepare("SELECT id,status FROM bv_renders WHERE project_id=? AND status IN ('submitting','queued','rendering') ORDER BY created_at DESC LIMIT 1").bind(q.id).first<any>();if(active)return j({success:false,error:"A render is already in progress",render:active},409);await e.DB.prepare("UPDATE bv_projects SET status='image_ready',updated_at=? WHERE id=? AND user_id=?").bind(now,q.id,u.id).run()}const locked=await e.DB.prepare("UPDATE bv_projects SET status='rendering',updated_at=? WHERE id=? AND user_id=? AND status<>'rendering'").bind(now,q.id,u.id).run();if(!locked.meta.changes)return j({success:false,error:"A render is already in progress"},409);const id=crypto.randomUUID(),placeholder="pending:"+id;await e.DB.prepare("INSERT INTO bv_renders VALUES(?,?,?,?,?,?,?,?)").bind(id,q.id,placeholder,"submitting",null,null,null,now,now).run();try{const rid=await render(e,q);await e.DB.prepare("UPDATE bv_renders SET provider_render_id=?,status='queued',updated_at=? WHERE id=?").bind(rid,n(),id).run();return j({success:true,render:{id,status:"queued"}},201)}catch(err){await e.DB.batch([e.DB.prepare("UPDATE bv_renders SET status='failed',error_message='Render submission failed',updated_at=? WHERE id=?").bind(n(),id),e.DB.prepare("UPDATE bv_projects SET status='image_ready',updated_at=? WHERE id=?").bind(n(),q.id)]);throw err}}
x=p.match(/^\/api\/projects\/([^/]+)\/audio\/upload-url$/);if(x&&m==="POST"){const u=await auth(r,e),q=await project(e,u,x[1]);if(!q)return j({success:false,error:"Project not found"},404);stage="audio.upload";const b=await body(r),name=reqs(b.filename,"filename",1,160);return j({success:true,...await upload(e,name)})}
x=p.match(/^\/api\/projects\/([^/]+)\/audio\/complete$/);if(x&&m==="POST"){const u=await auth(r,e),q=await project(e,u,x[1]);if(!q)return j({success:false,error:"Project not found"},404);stage="audio.complete";const b=await body(r),id=reqs(b.source_id,"source_id",1,200),s=await source(e,id);if(s.status!=="ready")return j({success:false,error:"Audio is not ready",status:s.status},409);await e.DB.prepare("UPDATE bv_projects SET audio_source_id=?,audio_source_url=?,audio_name=?,audio_type=?,audio_size=?,audio_duration=?,status='audio_ready',updated_at=? WHERE id=?").bind(id,s.source,String(b.name||"audio"),String(b.type||"audio/*"),Number(b.size)||null,Number(s.duration)||null,n(),q.id).run();return j({success:true,audio:{duration:s.duration||null}})}
x=p.match(/^\/api\/renders\/([^/]+)$/);if(x&&m==="GET"){stage="render.status";const u=await auth(r,e),q=await e.DB.prepare("SELECT r.* FROM bv_renders r JOIN bv_projects p ON p.id=r.project_id WHERE r.id=? AND p.user_id=?").bind(x[1],u.id).first<any>();if(!q)return j({success:false,error:"Render not found"},404);if(q.status==="submitting"||q.provider_render_id.startsWith("pending:"))return j({success:true,render:q});const s=await renderStatus(e,q.provider_render_id),st=s.status==="done"?"done":s.status==="failed"?"failed":s.status||"queued";await e.DB.prepare("UPDATE bv_renders SET status=?,output_url=?,poster_url=?,error_message=?,updated_at=? WHERE id=?").bind(st,s.url||q.output_url,s.poster||q.poster_url,s.error||null,n(),q.id).run();if(st==="done"||st==="failed")await e.DB.prepare("UPDATE bv_projects SET status=?,updated_at=? WHERE id=?").bind(st==="done"?"rendered":"image_ready",n(),q.project_id).run();return j({success:true,render:{...q,status:st,output_url:s.url||q.output_url,poster_url:s.poster||q.poster_url,error_message:s.error||q.error_message}})}
if(p.startsWith("/api/"))return j({success:false,error:"Not found"},404);return e.ASSETS.fetch(r)}catch(err){if(err instanceof Response)return err;const ae=err instanceof AppError?err:null;console.error(JSON.stringify({event:"request_error",request_id:requestId,stage:ae?.stage||stage,status:ae?.status||500,error:err instanceof Error?err.message:String(err)}));return j({success:false,error:ae?.message||"Internal server error",request_id:requestId},ae?.status||500,{"x-request-id":requestId})}}};